// [META] since:2026-05-02 | owner:cli-team | stable:false
// [WHY] 为 init 提供 per-runtime assistant bootstrap 资产生成，让 Claude/Codex/generic 助手快速连接项目上下文

import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { InitAsset } from './reconciler.js';

export type AssistantProfile = 'claude' | 'codex' | 'generic';

interface FileWriteAction {
  targetPath: string;
  content: string;
}

export interface AssistantPlan {
  assets: InitAsset[];
  writes: FileWriteAction[];
}

interface AssistantAssetDef {
  runtime: AssistantProfile;
  fileName: string;
  generate: (rootDir: string, profileName?: string) => string;
}

function hashText(text: string): string {
  return createHash('sha256').update(text).digest('hex').slice(0, 12);
}

function safeReadText(filePath: string): string | undefined {
  if (!existsSync(filePath)) {
    return undefined;
  }
  return readFileSync(filePath, 'utf8');
}

function generateClaudeContext(_rootDir: string, profileName?: string): string {
  return `# CodeMap - Claude Context

> Auto-generated by \`mycodemap init\`. Review and copy relevant sections into your project CLAUDE.md.

## Project Setup

- **Profile:** ${profileName ?? 'generic'}
- **Env Contract:** \`.mycodemap/env-contract.json\`
- **Rules:** \`.mycodemap/rules/\`
- **Init Receipt:** \`.mycodemap/status/init-last.json\`

## Quick Commands

\`\`\`bash
mycodemap doctor      # Diagnose project health
mycodemap generate    # Generate code map
mycodemap preview     # Preview without config
\`\`\`

## Agent Context

For subagent retrieval of project conventions, see:
- \`.mycodemap/env-contract.json\` — project environment contract
- \`.mycodemap/rules/\` — project-specific rules

> This file is a copy-paste suggestion. Do NOT auto-rewrite your CLAUDE.md.
`;
}

function generateAgentsContext(_rootDir: string, profileName?: string): string {
  return `# CodeMap - Agents Context

> Auto-generated by \`mycodemap init\`. Review and copy relevant sections into your project AGENTS.md.

## Project Setup

- **Profile:** ${profileName ?? 'generic'}
- **Env Contract:** \`.mycodemap/env-contract.json\`
- **Rules:** \`.mycodemap/rules/\`
- **Init Receipt:** \`.mycodemap/status/init-last.json\`

## Quick Commands

\`\`\`bash
mycodemap doctor      # Diagnose project health
mycodemap generate    # Generate code map
mycodemap preview     # Preview without config
\`\`\`

## Subagent Retrieval

For delegated agents, query the environment contract:
\`\`\`bash
cat .mycodemap/env-contract.json
\`\`\`

> This file is a copy-paste suggestion. Do NOT auto-rewrite your AGENTS.md.
`;
}

function generateClaudeHookExample(): string {
  return JSON.stringify(
    {
      _comment:
        'Example Claude Code SubagentStart hook — NOT active by default. Copy to .claude/settings.json to enable.',
      hooks: {
        SubagentStart: [
          {
            matcher: '',
            hooks: [
              {
                type: 'command',
                command:
                  'cat .mycodemap/env-contract.json 2>/dev/null || echo \'{"status":"no-contract"}\'',
              },
            ],
          },
        ],
      },
    },
    null,
    2
  );
}

function generateCodexAgentExample(): string {
  return `# Example Codex agent developer_instructions — NOT active by default.
# Copy to .codex/agents/ to enable subagent contract retrieval.

[developer_instructions]
retrieval_command = "cat .mycodemap/env-contract.json 2>/dev/null || echo 'no contract'"
description = "Retrieve project environment contract for delegated agents"
`;
}

const ASSISTANT_ASSETS: AssistantAssetDef[] = [
  {
    runtime: 'claude',
    fileName: 'claude-context.md',
    generate: (rootDir, profileName) => generateClaudeContext(rootDir, profileName),
  },
  {
    runtime: 'codex',
    fileName: 'agents-context.md',
    generate: (rootDir, profileName) => generateAgentsContext(rootDir, profileName),
  },
  {
    runtime: 'claude',
    fileName: 'claude-hook-example.json',
    generate: () => generateClaudeHookExample(),
  },
  {
    runtime: 'codex',
    fileName: 'codex-agent-example.toml',
    generate: () => generateCodexAgentExample(),
  },
];

function assetKey(fileName: string): string {
  const base = fileName.replace(/\.[^.]+$/, '');
  return `assistant:${base}`;
}

export function createAssistantPlan(
  rootDir: string,
  assistantProfile?: AssistantProfile,
  profileName?: string
): AssistantPlan {
  const assets: InitAsset[] = [];
  const writes: FileWriteAction[] = [];

  for (const def of ASSISTANT_ASSETS) {
    if (assistantProfile && def.runtime !== assistantProfile) {
      continue;
    }

    const targetPath = path.join(rootDir, '.mycodemap', 'assistants', def.fileName);
    const content = def.generate(rootDir, profileName);
    const key = assetKey(def.fileName);
    const currentText = safeReadText(targetPath);

    if (currentText === content) {
      assets.push({
        key,
        label: def.fileName,
        status: 'already-synced',
        ownership: 'tool-owned',
        origin: 'assistant-bootstrap',
        path: targetPath,
        details: [`${def.fileName} 已同步，无需更新`],
        hash: hashText(content),
      });
      continue;
    }

    if (currentText !== undefined) {
      assets.push({
        key,
        label: def.fileName,
        status: 'conflict',
        ownership: 'tool-owned',
        origin: 'assistant-bootstrap',
        path: targetPath,
        details: [
          `检测到 .mycodemap/assistants/${def.fileName} 与预期内容存在差异；本次不会自动覆盖`,
        ],
        hash: hashText(content),
        manualAction: `手动审阅 .mycodemap/assistants/${def.fileName} 的内容，确认后可删除该文件再重跑 init`,
      });
      continue;
    }

    writes.push({ targetPath, content });
    assets.push({
      key,
      label: def.fileName,
      status: 'installed',
      ownership: 'tool-owned',
      origin: 'assistant-bootstrap',
      path: targetPath,
      details: [`将生成 .mycodemap/assistants/${def.fileName}`],
      hash: hashText(content),
      rollbackHint: `如需回退，可删除 .mycodemap/assistants/${def.fileName}`,
    });
  }

  return { assets, writes };
}

export async function applyAssistantPlan(plan: AssistantPlan): Promise<void> {
  for (const writeAction of plan.writes) {
    await mkdir(path.dirname(writeAction.targetPath), { recursive: true });
    await writeFile(writeAction.targetPath, writeAction.content, 'utf8');
  }
}
