// [META] since:2026-05-10 | owner:cli-team | stable:false
// [WHY] Interface contract for the `agent-metrics` command family

import type { CommandContract } from '../types.js';

export const agentMetricsContract: CommandContract = {
  name: 'agent-metrics',
  description: '分析 CodeMap 查询响应的估算 LLM token 成本',
  stable: true,
  args: [],
  flags: [
    {
      name: 'json',
      short: 'j',
      long: 'json',
      description: 'JSON 格式输出',
      type: 'boolean',
      defaultValue: false,
    },
    {
      name: 'human',
      long: 'human',
      description: '强制人类可读输出',
      type: 'boolean',
      defaultValue: false,
    },
    {
      name: 'max-tokens-per-query',
      long: 'max-tokens-per-query',
      description: '报告路径上允许的单次查询最大估算 token 数；仅 bare/report 路径支持',
      type: 'number',
    },
  ],
  outputShape: {
    description: 'Agent-metrics report or token-run output',
    type: 'object',
    properties: [
      { name: 'schemaVersion', type: 'string', description: 'Output schema version' },
      { name: 'runId', type: 'string', description: 'Persisted run identifier' },
      { name: 'recordedAt', type: 'string', description: 'Run timestamp' },
      { name: 'sampleSetVersion', type: 'string', description: 'Built-in sample-set version' },
      { name: 'estimatorVersion', type: 'string', description: 'Token estimation heuristic version' },
      {
        name: 'rows',
        type: 'array',
        nullable: true,
        description: 'Per-query report rows (report mode)',
        items: {
          name: 'row',
          type: 'object',
          properties: [
            { name: 'queryType', type: 'string' },
            { name: 'commandSlug', type: 'string' },
            { name: 'responseSizeBytes', type: 'number' },
            { name: 'rawCharCount', type: 'number' },
            { name: 'estimatedInputTokens', type: 'number' },
            { name: 'estimatedOutputTokens', type: 'number' },
            { name: 'estimatedTotalTokens', type: 'number' },
          ],
        },
      },
      {
        name: 'items',
        type: 'array',
        nullable: true,
        description: 'Per-query measurement rows (token mode)',
        items: {
          name: 'item',
          type: 'object',
          properties: [
            { name: 'queryType', type: 'string' },
            { name: 'commandSlug', type: 'string' },
            { name: 'responseSizeBytes', type: 'number' },
            { name: 'rawCharCount', type: 'number' },
            { name: 'estimatedInputTokens', type: 'number' },
            { name: 'estimatedOutputTokens', type: 'number' },
            { name: 'estimatedTotalTokens', type: 'number' },
          ],
        },
      },
      {
        name: 'totals',
        type: 'object',
        properties: [
          { name: 'queryCount', type: 'number' },
          { name: 'responseSizeBytes', type: 'number' },
          { name: 'rawCharCount', type: 'number' },
          { name: 'estimatedInputTokens', type: 'number' },
          { name: 'estimatedOutputTokens', type: 'number' },
          { name: 'estimatedTotalTokens', type: 'number' },
        ],
      },
      {
        name: 'queryTypeSummaries',
        type: 'array',
        nullable: true,
        description: 'Grouped report summaries by query type (report mode)',
        items: {
          name: 'queryTypeSummary',
          type: 'object',
          properties: [
            { name: 'queryType', type: 'string' },
            { name: 'queryCount', type: 'number' },
            { name: 'historicalSampleCount', type: 'number' },
            { name: 'p50EstimatedTotalTokens', type: 'number' },
            { name: 'p95EstimatedTotalTokens', type: 'number' },
            { name: 'avgResponseSizeBytes', type: 'number' },
            { name: 'minResponseSizeBytes', type: 'number' },
            { name: 'maxResponseSizeBytes', type: 'number' },
            { name: 'avgRawCharCount', type: 'number' },
            { name: 'minRawCharCount', type: 'number' },
            { name: 'maxRawCharCount', type: 'number' },
            { name: 'avgEstimatedTotalTokens', type: 'number' },
            { name: 'minEstimatedTotalTokens', type: 'number' },
            { name: 'maxEstimatedTotalTokens', type: 'number' },
            { name: 'avgExecutionTimeMs', type: 'number' },
          ],
        },
      },
      {
        name: 'queryTypeTrends',
        type: 'array',
        nullable: true,
        description: 'Latest-versus-previous grouped token trends by query type (report mode)',
        items: {
          name: 'queryTypeTrend',
          type: 'object',
          properties: [
            { name: 'queryType', type: 'string' },
            { name: 'latestEstimatedTotalTokens', type: 'number' },
            { name: 'previousEstimatedTotalTokens', type: 'number', nullable: true },
            { name: 'deltaEstimatedTotalTokens', type: 'number', nullable: true },
            { name: 'deltaPercent', type: 'number', nullable: true },
            { name: 'baselineAvailable', type: 'boolean' },
          ],
        },
      },
      {
        name: 'highestCostQueryTypes',
        type: 'array',
        nullable: true,
        description: 'Top advisory query-type cost rankings from the latest run (report mode)',
        items: {
          name: 'highestCostQueryType',
          type: 'object',
          properties: [
            { name: 'queryType', type: 'string' },
            { name: 'estimatedTotalTokens', type: 'number' },
            { name: 'riskNote', type: 'string' },
          ],
        },
      },
      {
        name: 'highestCostRows',
        type: 'array',
        nullable: true,
        description: 'Top advisory per-row cost rankings from the latest run (report mode)',
        items: {
          name: 'highestCostRow',
          type: 'object',
          properties: [
            { name: 'queryType', type: 'string' },
            { name: 'commandSlug', type: 'string' },
            { name: 'estimatedTotalTokens', type: 'number' },
            { name: 'riskNote', type: 'string' },
          ],
        },
      },
      {
        name: 'gate',
        type: 'object',
        nullable: true,
        description: 'CI-facing gate verdict metadata for report mode',
        properties: [
          { name: 'verdict', type: 'string' },
          { name: 'warnOnly', type: 'boolean' },
          { name: 'threshold', type: 'number', nullable: true },
          { name: 'violationCount', type: 'number' },
          {
            name: 'maxRow',
            type: 'object',
            nullable: true,
            properties: [
              { name: 'queryType', type: 'string' },
              { name: 'commandSlug', type: 'string' },
              { name: 'estimatedTotalTokens', type: 'number' },
            ],
          },
          {
            name: 'violations',
            type: 'array',
            nullable: true,
            items: {
              name: 'violation',
              type: 'object',
              properties: [
                { name: 'queryType', type: 'string' },
                { name: 'commandSlug', type: 'string' },
                { name: 'estimatedTotalTokens', type: 'number' },
              ],
            },
          },
        ],
      },
    ],
  },
  errorCodes: [
    { code: 'AGENT_METRICS_STORAGE_UNSUPPORTED', description: 'Configured storage cannot persist or read agent-metrics runs' },
    { code: 'AGENT_METRICS_SAMPLE_FAILED', description: 'One of the fixed built-in samples failed to execute' },
    { code: 'AGENT_METRICS_EMPTY_RUN', description: 'The latest persisted run exists but has no readable detail rows' },
    { code: 'AGENT_METRICS_REPORT_MISSING', description: 'No persisted agent-metrics run exists yet for explicit report mode' },
  ],
  examples: [
    'codemap agent-metrics',
    'codemap agent-metrics report --json',
    'codemap agent-metrics report --max-tokens-per-query 160 --json',
    'codemap agent-metrics token',
  ],
};
